Get filenames for file hashes
polarityio/virustotal pull request #8
Opened 2021-10-25 17:50 UTC by ntsmith7

2021-11-05 03:05 UTC, sarus requested changes

2021-11-05 03:05 UTC, sarus commented on templates/virustotal.hbs
> +          <span class="p-value">{{name}}</span>
It can be difficult to tell what the filenames are since long names wrap and there is no visual distinction between filenames other than a newline.  For example,

![image](https://user-images.githubusercontent.com/306319/140451456-1d607a8d-09f5-4cd3-853d-78f81062f662.png)

In this image the long hash filename is a single filename but because it wraps it looks like two different filenames.

I think we need to change the style here a bit to make it clear what the distinct filenames are.

2021-11-05 03:05 UTC, sarus commented on templates/virustotal.hbs
> +        {{action "fetchNames"}}
Really like how you put the filename information under a new tab.  I think instead of having the button we should just load the filenames when the user clicks on the tab.  We should also add a loading message in case there is latency so the user knows that data is loading.

2021-11-30 18:17 UTC, penwoodjon reviewed
Outside of removing some potentially unused code, it is working well for me 👍.

2021-11-30 18:17 UTC, penwoodjon commented on components/virustotal.js
> +    fetchNames: function () {
I'm not seeing where this function is used or a corresponding onMessage function 🤔. I would remove this if it's not being used.

2021-11-30 18:17 UTC, penwoodjon commented on styles/virustotal.less
> +.filenames-btn {
I'm not seeing `filenames-btn` or `filename-title` in the template file.  I would remove this if it's not being used.

2021-11-30 18:21 UTC, penwoodjon commented on templates/virustotal.hbs
> +        <a href="{{details.detectionsLink}}">View Scans in VirusTotal
I would change this link to `details.detailsLink` from in the [integration.js payload](https://github.com/polarityio/virustotal/blob/master/integration.js#L560), as the filename info is on that tab.

2021-12-01 17:00 UTC, penwoodjon approved these changes

2021-12-01 17:00 UTC, merged